import './globals.css';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

import AnswerContextProvider from '@/contexts/AnswerContext';
import CandidateContextProvider from '@/contexts/CandidateContext';

import Providers from './providers';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // Add desired weights
  variable: '--font-poppins', // Define a CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className='font-poppins'
      >
        <AnswerContextProvider>
          <CandidateContextProvider>
            <Providers>
              <Toaster position='top-center'/>
              { children }
            </Providers>
          </CandidateContextProvider>
        </AnswerContextProvider>
      </body>
    </html>
  );
}
